/**
 * HireShield-AI — Professional PDF Audit Report Generator
 * Generates an official, publication-ready security report using jsPDF.
 */
import { jsPDF } from 'jspdf';

/**
 * Generate and download an official PDF Risk Assessment Report
 * @param {Object} report The assessment report data
 */
export const generateAssessmentPDF = (report) => {
  if (!report) return;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // --- Helpers ---
  const addHeader = () => {
    // Top Brand Bar
    doc.setFillColor(15, 23, 42); // slate-900 / dark primary
    doc.rect(0, 0, pageWidth, 55, 'F');

    // Brand Name
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(255, 255, 255);
    doc.text('HireShield.ai', margin, 34);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text('AI-Powered Opportunity Credibility & Scam Defense', margin + 110, 34);

    // Official Report Tag
    doc.setFontSize(8);
    doc.setTextColor(226, 232, 240);
    doc.text('OFFICIAL VERIFICATION REPORT', pageWidth - margin - 150, 34);
  };

  const addFooter = (pageNum = 1) => {
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, pageHeight - 35, pageWidth - margin, pageHeight - 35);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      'Generated by HireShield-AI Security Assessment Engine • https://hireshield.ai',
      margin,
      pageHeight - 22
    );
    doc.text(`Page ${pageNum}`, pageWidth - margin - 35, pageHeight - 22);
  };

  // 1. Draw Page Header
  addHeader();
  y = 75;

  // 2. Report Metadata Bar
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, y, contentWidth, 38, 4, 4, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, y, contentWidth, 38, 4, 4, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('ASSESSMENT ID', margin + 12, y + 15);
  doc.text('DATE GENERATED', margin + 140, y + 15);
  doc.text('TARGET OPPORTUNITY', margin + 270, y + 15);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(30, 41, 59);
  doc.text(report.id || 'HS-SCAN-2026-X', margin + 12, y + 28);
  doc.text(report.timestamp || new Date().toLocaleString(), margin + 140, y + 28);
  
  const titleText = `${report.jobTitle || report.title || 'Job Assessment'} (${report.company || 'Unknown'})`;
  const truncatedTitle = titleText.length > 35 ? titleText.substring(0, 32) + '...' : titleText;
  doc.text(truncatedTitle, margin + 270, y + 28);

  y += 52;

  // 3. Overall Risk Assessment Summary Box
  const score = Math.round(Number(report.score ?? report.riskScore ?? 0));
  let badgeColor = [34, 197, 94]; // Green for Low
  let riskText = 'LOW RISK';
  let recommendation = report.verdict || report.recommendation || 'APPLY WITH NORMAL DILIGENCE';

  if (score >= 70) {
    badgeColor = [239, 68, 68]; // Red for High
    riskText = 'HIGH RISK / SCAM';
  } else if (score >= 35) {
    badgeColor = [245, 158, 11]; // Amber for Moderate
    riskText = 'MODERATE RISK';
  }

  // Summary Container
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, y, contentWidth, 80, 6, 6, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, y, contentWidth, 80, 6, 6, 'S');

  // Score Badge
  doc.setFillColor(badgeColor[0], badgeColor[1], badgeColor[2]);
  doc.roundedRect(margin + 16, y + 14, 85, 52, 6, 6, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text(`${score}`, margin + 58, y + 42, { align: 'center' });
  doc.setFontSize(8);
  doc.text('/ 100 RISK', margin + 58, y + 55, { align: 'center' });

  // Verdict Details
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(badgeColor[0], badgeColor[1], badgeColor[2]);
  doc.text(`${riskText} — ${recommendation}`, margin + 115, y + 28);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);
  const summaryExplanation = report.summary ||
    'Hybrid multi-layer analysis evaluated job listing content, company public records, domain reputation, and recruiter credentials.';
  const wrappedSummary = doc.splitTextToSize(summaryExplanation, contentWidth - 130);
  doc.text(wrappedSummary, margin + 115, y + 44);

  y += 95;

  // 4. Verification Matrix Table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('Verification Checklist & Signals', margin, y);
  y += 12;

  const matrixItems = report.verificationMatrix || [
    { title: 'Corporate Registry', status: 'verified', details: 'Cross-referenced against registry records.' },
    { title: 'Recruiter Authenticity', status: score > 50 ? 'warning' : 'verified', details: 'Corporate email and identity check.' },
    { title: 'Domain & SSL Trust', status: score > 50 ? 'suspicious' : 'verified', details: 'WHOIS registration and certificate safety.' },
    { title: 'Financial Requirements', status: score > 50 ? 'warning' : 'verified', details: 'Absence of placement fees or check deposit requests.' },
  ];

  matrixItems.slice(0, 4).forEach((item, idx) => {
    const itemX = margin + (idx % 2) * (contentWidth / 2 + 5);
    const itemY = y + Math.floor(idx / 2) * 36;

    doc.setFillColor(248, 250, 252);
    doc.roundedRect(itemX, itemY, contentWidth / 2 - 5, 30, 4, 4, 'F');
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(itemX, itemY, contentWidth / 2 - 5, 30, 4, 4, 'S');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(30, 41, 59);
    doc.text(item.title || 'Verification Item', itemX + 8, itemY + 13);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(100, 116, 139);
    const det = item.details || item.status || 'Verified';
    doc.text(det.length > 40 ? det.substring(0, 37) + '...' : det, itemX + 8, itemY + 23);
  });

  y += 82;

  // 5. Identified Risk Factors & Red Flags
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('Identified Risk Factors & Behavioral Signals', margin, y);
  y += 12;

  const factors = report.riskFactors || [];

  if (factors.length === 0) {
    doc.setFillColor(240, 253, 244);
    doc.roundedRect(margin, y, contentWidth, 32, 4, 4, 'F');
    doc.setDrawColor(187, 247, 208);
    doc.roundedRect(margin, y, contentWidth, 32, 4, 4, 'S');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(22, 101, 52);
    doc.text('✓ No High-Severity Risk Factors Detected', margin + 12, y + 20);
    y += 42;
  } else {
    factors.slice(0, 5).forEach((rf) => {
      const isHigh = (rf.severity || '').toLowerCase() === 'high';
      const isMedium = (rf.severity || '').toLowerCase() === 'medium';
      
      const itemBg = isHigh ? [254, 242, 242] : isMedium ? [254, 243, 199] : [241, 245, 249];
      const itemBorder = isHigh ? [254, 202, 202] : isMedium ? [253, 230, 138] : [226, 232, 240];
      const textColor = isHigh ? [153, 27, 27] : isMedium ? [146, 64, 14] : [30, 41, 59];

      doc.setFillColor(itemBg[0], itemBg[1], itemBg[2]);
      doc.roundedRect(margin, y, contentWidth, 42, 4, 4, 'F');
      doc.setDrawColor(itemBorder[0], itemBorder[1], itemBorder[2]);
      doc.roundedRect(margin, y, contentWidth, 42, 4, 4, 'S');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(textColor[0], textColor[1], textColor[2]);
      const titleLine = `[${(rf.severity || 'SIGNAL').toUpperCase()}] ${rf.title || rf.category || 'Risk Indicator'}`;
      doc.text(titleLine, margin + 10, y + 14);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(71, 85, 105);
      const desc = rf.description || rf.evidence || '';
      const wrappedDesc = doc.splitTextToSize(desc, contentWidth - 20);
      doc.text(wrappedDesc.slice(0, 2), margin + 10, y + 26);

      y += 48;
    });
  }

  // 6. Security Advisory & Next Steps
  y = Math.max(y, pageHeight - 130);
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(margin, y, contentWidth, 68, 4, 4, 'F');
  doc.setDrawColor(203, 213, 225);
  doc.roundedRect(margin, y, contentWidth, 68, 4, 4, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(30, 41, 59);
  doc.text('Recommended Actions for Candidate:', margin + 12, y + 16);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(71, 85, 105);
  const advice = score >= 70
    ? '1. DO NOT send money, pay registration fees, or purchase equipment through recruiter links.\n2. Cease contact immediately if requested to communicate exclusively on Telegram/WhatsApp.\n3. Verify open positions directly on the company\'s official website (careers section).'
    : score >= 35
    ? '1. Proceed with caution. Verify the recruiter\'s official corporate email domain.\n2. Confirm interview invites occur through standard video conference platforms (e.g. Google Meet, Zoom, Teams).\n3. Never share bank account or sensitive personal credentials prior to formal verified offer.'
    : '1. Listing demonstrates consistent authenticity indicators across domain, recruiter, and text signals.\n2. Always verify any subsequent banking or offer documentation during the onboarding stage.';

  const splitAdvice = doc.splitTextToSize(advice, contentWidth - 24);
  doc.text(splitAdvice, margin + 12, y + 28);

  // 7. Footer
  addFooter(1);

  // 8. Trigger Download
  const filenameSafe = (report.company || 'Job')
    .replace(/[^a-zA-Z0-9]/g, '_')
    .substring(0, 20);
  const filename = `HireShield_Risk_Report_${filenameSafe}_${score}pts.pdf`;

  doc.save(filename);
};
